### ISSUE TITLE
Gun information: projectile scatter

### ISSUE THREAD

**Issue by roalyr** [biqqles/wingman#1]
Some weapons have a degree of projectile scattering (deviation from shooting line), this information would be beneficial to be displayed.

**Comment by biqqles** [comment]
Yeah, this would be useful! It'll be added in the forthcoming update to the Guns database page.

**Comment by roalyr** [comment]
That said, how about adjustable data columns? Switch on and off whatever data is required.

**Comment by biqqles** [comment]
Do you have any UI ideas for this? It seems like a pretty unusual thing to do with tables. The obvious way would be a stack of checkboxes but that would take up a lot of room for little benefit. Columns can and should be movable, though.

**Comment by roalyr** [comment]
The way it is made in file managers? Like, in nautilus or caja or thunar? Right click on the table header and check whatever you need?

**Comment by biqqles** [comment]
OK, I'm going to push an implementation of the original suggestion and close this. Please make another issue for the second suggestion 🙂
