### ISSUE TITLE
Build: Python 3.9 incompatibility

### ISSUE THREAD

**Issue by dd84ai** [biqqles/wingman#30]
I can't launch Wingman.exe, due to appearing error, Api-ms-win-core-path-l1-1-0.dll is missing.
Well, and Wingman\python39.dll is missing
Windows 7

Wait a second, I know the reason for at least second error(highly probably first error due to the same reason)
3.9 python is not compatible with windows 7
Could you downgrade python to 3.8.6?

P.S. googled, https://bugs.python.org/issue40740
It is indeed all 3.9 python problem for both issues

**Comment by biqqles** [comment]
Oh, drat, I did not realise Python 3.9 ended support for Windows 7. Thanks.
